"""Smart Onboarding Service — account scan + auto-generate guidelines."""

from __future__ import annotations

import logging
from datetime import date
from pathlib import Path

from app.config import settings
from app.database import get_db
from app.services.marketing_intelligence import (
    CampaignObjective,
    CampaignPhase,
    MarketingIntelligenceService,
)

logger = logging.getLogger(__name__)

_mi = MarketingIntelligenceService()


class OnboardingService:
    """Scan accounts and generate initial guidelines from campaign data."""

    async def scan_account(
        self, account_id: str, campaigns: list[dict]
    ) -> dict:
        """Analyze campaigns and detect goals/phases.

        Args:
            account_id: Google Ads customer ID
            campaigns: List of campaign dicts from GoogleAdsService.get_campaigns()

        Returns:
            Scan result dict with detected goals and phases per campaign.
        """
        results = []
        db = await get_db()
        try:
            for c in campaigns:
                campaign_id = c.get("id", "")
                name = c.get("name", "")
                conversions = c.get("conversions", 0.0)
                cost_micros = c.get("cost_micros", 0)
                cost = cost_micros / 1_000_000 if cost_micros else 0

                goal = _mi.detect_campaign_goal(c)
                phase = _mi.detect_campaign_phase(
                    c, conversions_30d=conversions, cost_30d=cost
                )

                # Store in campaign_goals table
                await db.execute(
                    """INSERT OR REPLACE INTO campaign_goals
                       (account_id, campaign_id, campaign_name, objective, phase,
                        phase_detected_at, updated_at)
                       VALUES (?, ?, ?, ?, ?, datetime('now'), datetime('now'))""",
                    (account_id, campaign_id, name, goal.value, phase.value),
                )

                results.append({
                    "campaign_id": campaign_id,
                    "campaign_name": name,
                    "objective": goal.value,
                    "phase": phase.value,
                    "status": c.get("status", ""),
                    "budget_micros": c.get("budget_micros", 0),
                    "bidding_strategy": c.get("bidding_strategy", ""),
                    "impressions": c.get("impressions", 0),
                    "clicks": c.get("clicks", 0),
                    "conversions": conversions,
                    "cost": cost,
                })

            await db.commit()
        finally:
            await db.close()

        # Generate proactive insights
        insights = await _mi.generate_proactive_insights(account_id, campaigns)
        await _mi.store_insights(insights)

        return {
            "account_id": account_id,
            "campaigns_found": len(results),
            "campaigns": results,
            "alerts_generated": len(insights),
        }

    def generate_guidelines(
        self, account_id: str, account_name: str, campaigns: list[dict]
    ) -> dict[str, str]:
        """Generate markdown guidelines from scan data. No AI needed.

        Returns:
            Dict of {filename: content} to be written to disk.
        """
        files = {}

        # ── BUSINESS_CONTEXT.md ────────────────────────────────────
        active = [c for c in campaigns if c.get("status") == "ENABLED"]
        total_cost = sum(c.get("cost", 0) for c in campaigns)
        total_conversions = sum(c.get("conversions", 0) for c in campaigns)

        campaign_lines = []
        for c in active:
            cost = c.get("cost", 0)
            conv = c.get("conversions", 0)
            cpa = cost / conv if conv > 0 else 0
            campaign_lines.append(
                f"| {c['campaign_name']} | {c.get('status', 'ENABLED')} | "
                f"${c.get('budget_micros', 0) / 1_000_000:.0f}/day | "
                f"{c.get('bidding_strategy', 'N/A')} | "
                f"${cost:.0f} | {conv:.0f} | ${cpa:.0f} |"
            )

        campaigns_table = (
            "| Campaign | Status | Budget | Strategy | Cost (30d) | Conv (30d) | CPA |\n"
            "|----------|--------|--------|----------|------------|------------|-----|\n"
            + "\n".join(campaign_lines)
        )

        files["BUSINESS_CONTEXT.md"] = f"""# Business Context

## Account Overview
- **Account ID:** {account_id}
- **Account Name:** {account_name}
- **Active Campaigns:** {len(active)}
- **Total Spend (30d):** ${total_cost:,.2f}
- **Total Conversions (30d):** {total_conversions:.0f}

## Campaign Summary

{campaigns_table}

## Key Constraints
- (Add budget caps, compliance rules, brand guidelines here)

## Business Goals
- (Add primary business objectives here)

---
*Auto-generated by Google Ads Agent on {date.today().isoformat()}. Edit to add business context, goals, and constraints.*
"""

        # ── CAMPAIGN_GUIDELINES.md ─────────────────────────────────
        sections = []
        sections.append("# Campaign Guidelines\n")
        sections.append("## Global Rules\n")
        sections.append("- Wait minimum 7 days before evaluating bid strategy changes.")
        sections.append("- Do NOT make multiple change types in the same day.")
        sections.append("- Always check search terms before adding broad match keywords.")
        sections.append("- Confirm with user before pausing any active campaign.")
        sections.append("- Log all changes to the Change Log section of the relevant campaign.\n")

        for c in active:
            name = c.get("campaign_name", "Unknown")
            campaign_id = c.get("campaign_id", "")
            objective = c.get("objective", "unknown")
            phase = c.get("phase", "unknown")
            budget = c.get("budget_micros", 0) / 1_000_000
            strategy = c.get("bidding_strategy", "N/A")
            cost = c.get("cost", 0)
            conv = c.get("conversions", 0)
            cpa = cost / conv if conv > 0 else 0

            sections.append(f"\n---\n\n## {name}\n")
            sections.append(f"### Campaign ID\n{campaign_id}\n")
            sections.append(f"### Objective\n{objective.replace('_', ' ').title()}\n")
            sections.append(f"### Phase\n{phase.title()}\n")
            sections.append(f"### Budget & Bidding")
            sections.append(f"- Daily budget: ${budget:.0f}")
            sections.append(f"- Bidding strategy: {strategy}")
            sections.append(f"- Cost (30d): ${cost:.0f}")
            sections.append(f"- Conversions (30d): {conv:.0f}")
            if cpa > 0:
                sections.append(f"- CPA: ${cpa:.2f}\n")
            else:
                sections.append(f"- CPA: N/A\n")
            sections.append("### Targeting\n- (Add location and language targets)\n")
            sections.append("### Ad Copy Rules\n- (Add approved messaging and brand voice)\n")
            sections.append("### Negative Keywords\n- (Add campaign-specific negatives)\n")
            sections.append("### Change Log\n- (Changes will be logged here)\n")

        files["CAMPAIGN_GUIDELINES.md"] = "\n".join(sections)

        return files

    def write_guidelines(
        self, account_id: str, files: dict[str, str]
    ) -> list[str]:
        """Write guideline files to disk under data/guidelines/{account_id}/.

        Returns list of filenames written.
        """
        account_dir = settings.GUIDELINES_DIR / account_id
        account_dir.mkdir(parents=True, exist_ok=True)

        written = []
        for filename, content in files.items():
            path = account_dir / filename
            # Don't overwrite existing files — user may have customized them
            if path.exists():
                logger.info("Skipping existing guideline: %s", path)
                continue
            path.write_text(content, encoding="utf-8")
            written.append(filename)
            logger.info("Generated guideline: %s", path)

        return written

    async def run_full_onboarding(
        self,
        account_id: str,
        account_name: str,
        campaigns: list[dict],
    ) -> dict:
        """Run complete onboarding: scan + detect goals + generate guidelines.

        Args:
            account_id: Google Ads customer ID
            account_name: Account display name
            campaigns: Raw campaign data from GoogleAdsService

        Returns:
            Onboarding result dict.
        """
        # 1. Scan and detect goals/phases
        scan = await self.scan_account(account_id, campaigns)

        # 2. Generate guideline files (uses enriched scan data with goals/phases)
        enriched_campaigns = scan["campaigns"]
        files = self.generate_guidelines(account_id, account_name, enriched_campaigns)

        # 3. Write to disk
        written = self.write_guidelines(account_id, files)

        # 4. Update account last_synced
        db = await get_db()
        try:
            await db.execute(
                "UPDATE accounts_v2 SET last_synced = datetime('now') WHERE id = ?",
                (account_id,),
            )
            await db.commit()
        finally:
            await db.close()

        return {
            **scan,
            "account_name": account_name,
            "guidelines_generated": written,
        }
